apiVersion: v2
name: sample-app
description: A helm chart for Sample App
type: application
version: 0.0.1
appVersion: "1.0"
# dependencies:
# - name: sample-app-service
#   version: 0.0.1
#   alias: nest-service

